In [ ]:
pip install --upgrade "mlflow>=3.1"

In [31]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [32]:
import mlflow

# Print connection information
print(f"MLflow Tracking URI: {mlflow.get_tracking_uri()}")

MLflow Tracking URI: http://127.0.0.1:5000


In [37]:
import mlflow

mlflow.set_experiment("Classification")

2026/03/29 15:54:03 INFO mlflow.tracking.fluent: Experiment with name 'Classification' does not exist. Creating a new experiment.


<Experiment: artifact_location='mlflow-artifacts:/6', creation_time=1774779843405, experiment_id='6', last_update_time=1774779843405, lifecycle_stage='active', name='Classification', tags={}, workspace='default'>

In [38]:
import mlflow
print(mlflow.get_tracking_uri())

http://127.0.0.1:5000


In [10]:
import mlflow

# Print connection information
print(f"MLflow Tracking URI: {mlflow.get_tracking_uri()}")
print(f"Active Experiment: {mlflow.get_experiment_by_name('Classification-Model')}")

# Test logging
with mlflow.start_run():
    mlflow.log_param("test_param", "test_value")
    print("✓ Successfully connected to MLflow!")

MLflow Tracking URI: http://127.0.0.1:5000
Active Experiment: <Experiment: artifact_location='mlflow-artifacts:/2', creation_time=1774776658827, experiment_id='2', last_update_time=1774776711720, lifecycle_stage='deleted', name='Classification-Model', tags={}, workspace='default'>


2026/03/29 15:04:05 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet



✓ Successfully connected to MLflow!
🏃 View run resilient-stork-729 at: http://127.0.0.1:5000/#/experiments/3/runs/683241bbfcb442ce83dde9d23ee4b439
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3


In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


emi_df = pd.read_csv('D:\Emi Predict\Data Sets\emi_prediction_cleanafterFE.csv')
print(emi_df.shape)
features = [
    "monthly_salary","school_fees","college_fees","travel_expenses",
    "groceries_utilities","other_monthly_expenses",
    "current_emi_amount","credit_score","requested_amount","bank_balance","emergency_fund"
]

X = emi_df[features]
y_clf = emi_df['emi_eligibility']

X_train, X_test, y_train, y_test = train_test_split(
    X, y_clf, test_size=0.2, random_state=42
)
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)


<>:7: SyntaxWarning: invalid escape sequence '\E'
<>:7: SyntaxWarning: invalid escape sequence '\E'
C:\Users\Windows 10\AppData\Local\Temp\ipykernel_3364\2691417706.py:7: SyntaxWarning: invalid escape sequence '\E'
  emi_df = pd.read_csv('D:\Emi Predict\Data Sets\emi_prediction_cleanafterFE.csv')


(344653, 38)


In [40]:
accuracy = accuracy_score(y_test, y_pred_rf)
precision = precision_score(y_test, y_pred_rf,average='weighted')
recall = recall_score(y_test, y_pred_rf,average='weighted')
f1 = f1_score(y_test, y_pred_rf,average='weighted')

print("📊 Classification Metrics")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

# Full Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

📊 Classification Metrics
Accuracy  : 0.8515
Precision : 0.8094
Recall    : 0.8515
F1 Score  : 0.8285

Confusion Matrix:
[[50946     0  2405]
 [ 2265     0   717]
 [ 4851     0  7747]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     53351
           1       0.00      0.00      0.00      2982
           2       0.71      0.61      0.66     12598

    accuracy                           0.85     68931
   macro avg       0.53      0.52      0.52     68931
weighted avg       0.81      0.85      0.83     68931



c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


In [41]:
with mlflow.start_run(run_name='RF Classification'):
    mlflow.log_metric('accuracy', accuracy)
    mlflow.log_metric('precision', precision)
    mlflow.log_metric('recall', recall)

    mlflow.sklearn.log_model(rf_model,"Random Forest Regressor")

2026/03/29 15:55:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/29 15:55:47 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


🏃 View run RF Classification at: http://127.0.0.1:5000/#/experiments/6/runs/d106464b3f0342c0b52268dcf59146fa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


In [42]:
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

y_clf = y_clf.apply(lambda x: 1 if x >= 1 else 0).astype(int)

clf_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", xgb.XGBClassifier(
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        random_state=42,
        eval_metric="logloss"
    ))
])

clf_pipeline.fit(X_train, y_train)

print("Classification model saved")

# Predictions
y_pred = clf_pipeline.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred,average='weighted')
recall = recall_score(y_test, y_pred,average='weighted')
f1 = f1_score(y_test, y_pred,average='weighted')

print("📊 Classification Metrics")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Full Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification model saved
📊 Classification Metrics
Accuracy  : 0.8552
Precision : 0.8148
Recall    : 0.8552
F1 Score  : 0.8341

Confusion Matrix:
[[50627     0  2724]
 [ 2171     0   811]
 [ 4277     0  8321]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.95      0.92     53351
           1       0.00      0.00      0.00      2982
           2       0.70      0.66      0.68     12598

    accuracy                           0.86     68931
   macro avg       0.53      0.54      0.53     68931
weighted avg       0.81      0.86      0.83     68931



c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


In [45]:
with mlflow.start_run(run_name='XGB BOOST Classification'):
    mlflow.log_metric('accuracy', accuracy)
    mlflow.log_metric('precision', precision)
    mlflow.log_metric('recall', recall)

    mlflow.sklearn.log_model(clf_pipeline,"XGB Boost Classification")

2026/03/29 15:59:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/29 15:59:45 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


🏃 View run XGB BOOST Classification at: http://127.0.0.1:5000/#/experiments/6/runs/f00a55d776f146bfb72dc55414e5aac6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


In [46]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import pickle
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred,average='weighted')
recall = recall_score(y_test, y_pred,average='weighted')
f1 = f1_score(y_test, y_pred,average='weighted')

print("📊 Classification Metrics")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Full Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

📊 Classification Metrics
Accuracy  : 0.8447
Precision : 0.8036
Recall    : 0.8447
F1 Score  : 0.8230

Confusion Matrix:
[[50408     0  2943]
 [ 2220     0   762]
 [ 4779     0  7819]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.94      0.91     53351
           1       0.00      0.00      0.00      2982
           2       0.68      0.62      0.65     12598

    accuracy                           0.84     68931
   macro avg       0.52      0.52      0.52     68931
weighted avg       0.80      0.84      0.82     68931



c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


In [48]:
with mlflow.start_run(run_name='Logistic Regression'):
    mlflow.log_metric('accuracy', accuracy)
    mlflow.log_metric('precision', precision)
    mlflow.log_metric('recall', recall)

    mlflow.sklearn.log_model(model,"Logistic Regression Classification")

2026/03/29 16:00:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/29 16:00:23 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/6/runs/e5205444cb3d4b10a0b5e34a9a46d765
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/6


In [49]:
import mlflow

mlflow.set_experiment("Classification-Tuned")

2026/03/30 05:43:54 INFO mlflow.tracking.fluent: Experiment with name 'Classification-Tuned' does not exist. Creating a new experiment.


<Experiment: artifact_location='mlflow-artifacts:/7', creation_time=1774829636823, experiment_id='7', last_update_time=1774829636823, lifecycle_stage='active', name='Classification-Tuned', tags={}, workspace='default'>

In [50]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

import xgboost as xgb

# Target
y_clf = emi_df['emi_eligibility']
y_clf = y_clf.apply(lambda x: 1 if x >= 1 else 0).astype(int)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_clf, test_size=0.2, random_state=42
)

# Pipeline
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", xgb.XGBClassifier(
        random_state=42,
        eval_metric="logloss",
        use_label_encoder=False
    ))
])

# 🔥 Hyperparameter space
param_dist = {
    "model__n_estimators": [100, 200, 300, 500],
    "model__max_depth": [3, 4, 5, 6, 8],
    "model__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "model__subsample": [0.7, 0.8, 0.9, 1.0],
    "model__colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "model__gamma": [0, 0.1, 0.3, 0.5],
    "model__min_child_weight": [1, 3, 5, 7]
}

# Random Search
random_search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_dist,
    n_iter=70,              # increase to 50+ for better results
    scoring="f1",           # better than accuracy
    cv=3,
    verbose=2,
    n_jobs=-1,
    random_state=42
)

# Train
random_search.fit(X_train, y_train)

# Best model
xgb_model = random_search.best_estimator_
print("\nBest Parameters:")
print(random_search.best_params_)

# Evaluate
y_pre_xgb = xgb_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pre_xgb))

accuracy = accuracy_score(y_test, y_pre_xgb)
precision = precision_score(y_test, y_pre_xgb)
recall = recall_score(y_test, y_pre_xgb)
f1 = f1_score(y_test, y_pre_xgb)

print("📊 Classification Metrics")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pre_xgb))

# Full Report
print("\nClassification Report:")
print(classification_report(y_test, y_pre_xgb))

with mlflow.start_run(run_name='XGBBoost Classification'):
    mlflow.log_metric('accuracy', accuracy)
    mlflow.log_metric('precision', precision)
    mlflow.log_metric('recall', recall)
    mlflow.log_metric('f1', f1)

    mlflow.sklearn.log_model(xgb_model,"XGBBoost Classification")

Fitting 3 folds for each of 70 candidates, totalling 210 fits


c:\Users\Windows 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:200: UserWarning: [06:21:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



Best Parameters:
{'model__subsample': 0.8, 'model__n_estimators': 300, 'model__min_child_weight': 5, 'model__max_depth': 8, 'model__learning_rate': 0.05, 'model__gamma': 0.3, 'model__colsample_bytree': 0.9}

Accuracy: 0.8729889309599455
📊 Classification Metrics
Accuracy  : 0.8730
Precision : 0.7323
Recall    : 0.6904
F1 Score  : 0.7108

Confusion Matrix:
[[49419  3932]
 [ 4823 10757]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.93      0.92     53351
           1       0.73      0.69      0.71     15580

    accuracy                           0.87     68931
   macro avg       0.82      0.81      0.81     68931
weighted avg       0.87      0.87      0.87     68931



2026/03/30 06:21:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/30 06:21:48 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/30 06:23:51 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\WINDOW~1\AppData\Local\Temp\tmp9b8om7r7\model\model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.8.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback. 


🏃 View run XGBBoost Classification at: http://127.0.0.1:5000/#/experiments/7/runs/d16c2afa872245b4bdaf2c231e1b6c91
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/7
